root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"


[build]
    cmd = "go build -o ./application ./cmd/api/main.go"
    bin = "./application"
    delay = 1000 # ms
    exclude_dir = ["assets", "tmp", "vendor"]
    include_ext = ["go", "tpl", "tmpl", "html"]
    exclude_regex = ["_test\\.go"]


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
